version: "3.2"
services:
  py-mongo:
    build:
      context: /home/test/mooongo/mongo
    volumes:
      - /home/test/mooongo/mongo_data:/data/db
      - /home/test/mooongo/mongo_delete_later:/var/www/html
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
